### PR TITLE
Adds basic ISJ import script

### PR DESCRIPTION
**Pull request by sanak**
@mbasa (CC: @dkastl)
This is 2nd PR toward `feature/adjust-format` branch (#1).
- Added download/import ISJ scripts 
- Adjusted core sql files
- Modified `README.md`

### CODE REVIEW

**Comment by sanak** [comment]
@mbasa Thanks for merging #1.
I will switch this PR's target branch to master.

**Comment by sanak** [comment]
Oh, GitHub seems to switch target branch automatically.

**Comment by mbasa** [comment]
For specific data sets, it might be better to write a WIKI about it and just create a link. There might be other data sets that can be used for `pgGeocoder` in the future.

**Comment by sanak** [comment]
@mbasa Okay, sure.
At this moment, I write the data sources at the bottom part of `README.md`, but I will write Wiki also, later.
- https://github.com/mbasa/pgGeocoder/tree/feature/import-isj#data-sources

**Comment by mbasa** [comment]
@sanak thanks for rewriting the README to md in PR#1. When I originally wrote the README, I don't think GitHub supported markdown yet. :-)

**Comment by sanak** [comment]
@mbasa Okay, no problem. :-)
By the way, I noticed that this PR overwrite #1 `README.md` contents, but should I arrange it to keep original contents as much as possible ?

**Comment by sanak** [comment]
@mbasa (CC: @dkastl)
> By the way, I noticed that this PR overwrite #1 README.md contents, but should I arrange it to keep original contents as much as possible ?

Well, I will try this after finishing to write slides, so please wait until next week.

**Review by mbasa — APPROVED** [review]

**Pull request merged**
